@Test
public void testCompleted() throws Exception {
    final BasicFutureCallback<Object> callback = new BasicFutureCallback<>();
    final BasicFuture<Object> future = new BasicFuture<>(callback);
    Assert.assertFalse(future.isDone());
    final Object result = new Object();
    final Exception boom = new Exception();
    future.completed(result);
    future.failed(boom);
    Assert.assertTrue(callback.isCompleted());
    Assert.assertSame(result, callback.getResult());
    Assert.assertFalse(callback.isFailed());
    Assert.assertNull(callback.getException());
    Assert.assertFalse(callback.isCancelled());
    Assert.assertSame(result, future.get());
    Assert.assertTrue(future.isDone());
    Assert.assertFalse(future.isCancelled());
}
